# Generated by Django 4.2.3 on 2023-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_name_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='duration',
        ),
    ]
