# Generated by Django 4.2.4 on 2023-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_plan_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
